### ISSUE TITLE
Doesn't work... 

### ISSUE THREAD

**Issue by tiredcisadmin** [kerry/obsidian-confluence-sync#3]
The plugin seems to do nothing. When I run either command, nothing shows up in the console. Nothing shows up in Confluence either. How can I debug this?

**Comment by aduil** [comment]
It works on my side, you can use Wireshark to capture requests/responses to debug it

**Comment by remix9** [comment]
Hi, i catch js error
app.js:1 Uncaught (in promise) Error: Request failed, status 404
    at new t (app.js:1:2030716)
    at vK (app.js:1:2030908)
    at app.js:1:2031587
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)

all params in config set

**Comment by tiredcisadmin** [comment]
Apologies, been too buy to troubleshoot. If this is still on going whenever I finally have time I will do the Wireshark capture for you. There is noting special about my setup, so I am sure others must be having this issue. 

MacOS: Sonoma 14.6
HW: M1 Pro
Obsidian: 1.6.7
Conlfuence Sync: 1.0.8
Confluence: 7.19.26

**Comment by bheus** [comment]
I'm having the same issue. I'm using Confluence Server and I wonder if this plugin only supports Confluence Cloud
